### ISSUE TITLE
Failed to compile Android Studio CMake

### ISSUE THREAD

**Issue by bcortens** [viaduck/icu-cmake#6]
I have been trying to compile from within Android Studio using the recommended changes:

I copied the icu-cmake file to my android studio project and then modified my android studio CMakeLists as well as the top level CMakeLists for the icu-cmake folder.

Upon attempting to compile I receive this error:
**_C/C++: ld: error: undefined symbol: uconvmsg_dat_**

Here is my Project CMake file 

```
cmake_minimum_required(VERSION 3.22)

project(LanguageService LANGUAGES CXX)

include_directories(${PROJECT_SOURCE_DIR}/src/main/cpp/include)

add_library(
        MyLib
        SHARED
        src/main/cpp/MyLib.cpp
        src/main/cpp/MyLib.h)

add_subdirectory(third_party/icu-cmake)

target_link_libraries( 
        MyLib
        icu )
```

And the ICU CMake File

```
cmake_minimum_required(VERSION 3.22)
project(icu-cmake LANGUAGES CXX)

if (POLICY CMP0135)
    cmake_policy(SET CMP0135 OLD)
endif()

# cache variables
set(BUILD_ICU ON)
set(ICU_BUILD_VERSION 61.1)
set(ICU_CFG_OPTIONS "")
set(ICU_STATIC OFF)
set(ICU_CROSS_ARCH "${CMAKE_ANDROID_API}")
set(SYSTEM_ICU OFF)

list(INSERT CMAKE_MODULE_PATH 0 "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
list(INSERT CMAKE_MODULE_PATH 0 "${CMAKE_CURRENT_SOURCE_DIR}/cmake-modules")

add_library(icu INTERFACE)

if (SYSTEM_ICU)
    # try to find icu
    find_package(ICU COMPONENTS data uc i18n io REQUIRED)
else()

    if (BUILD_ICU)
        include(BuildICU)
    else()
        include(PrebuiltICU)
    endif()

    if (NOT ICU_STATIC)
        include(GNUInstallDirs)
        install(FILES ${ICU_LIBRARY_FILES} DESTINATION ${CMAKE_INSTALL_LIBDIR})
    endif()
endif()

target_link_libraries(icu INTERFACE ${ICU_LIBRARIES})
target_include_directories(icu INTERFACE ${ICU_INCLUDE_DIRS})
```

Do I need to make further modifications to the configuration?

**Comment by roussosalex** [comment]
> I copied the icu-cmake file to my android studio project 

I would recommend using a git submodule if possible, as it allows easily updating `icu-cmake` in the future. 

> and then modified my android studio CMakeLists as well as the **top level CMakeLists** for the icu-cmake folder.

You should not have to modify any files in the `icu-cmake` project, instead all options should be set either from your "android studio CMakeLists" or [globally via gradle cmake arguments](https://developer.android.com/reference/tools/gradle-api/4.2/com/android/build/api/dsl/ExternalNativeCmakeOptions#arguments%28kotlin.String%29)

> set(ICU_BUILD_VERSION 61.1)

Unless you need this exact version, you should use the most recent version 72.1

> undefined symbol: uconvmsg_dat

This may be related to the (default) selected STL library. 

So instead of editing the `icu-cmake` files, I would suggest trying these options in your `build.gradle` file:
```Groovy
android {
    defaultConfig {
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared", "-DBUILD_ICU=ON", "-DICU_BUILD_VERSION=72.1"
            }
        }
    }
}
```

**Comment by bcortens** [comment]
I suspect you may be right that it has something to do with the standard library. 

I have reverted to the unmodified CMakeLists file and added the arguments to the default config external native build however the issue of the missing symbols persists.

```
.cxx/Debug/t565w1s4/x86_64/src/main/cpp/icu-cmake/icu_cross/lib  -o ../../bin/uconv uconv.o uwmsg.o -L../../lib -licui18n -L../../lib -licuuc -L../../stubdata -licudata -lm   uconvmsg/libuconvmsg.a
  ld: error: undefined symbol: uconvmsg_dat
  >>> referenced by uconv.cpp:93 
```

I tried specifying C++11 as well without success...
I'm using NDK version 25.1.8937393 with SDK version 32

**Comment by roussosalex** [comment]
Just to make sure you are actually building the current version, try *carefully* deleting the build cache (`.cxx/Debug/...`) and reloading the project/cmake. If the error persists, please post the complete build log (as attachment).

**Comment by bcortens** [comment]
Hello,

I'm still seeing the error unfortunately.

I've attached the main build output as well as the manifest debug report.

[BuildLog.txt](https://github.com/viaduck/icu-cmake/files/10980393/BuildLog.txt)
[CMakeLists.txt](https://github.com/viaduck/icu-cmake/files/10980394/CMakeLists.txt)
[manifest-merger-debug-report.txt](https://github.com/viaduck/icu-cmake/files/10980395/manifest-merger-debug-report.txt)
[build.gradle.txt](https://github.com/viaduck/icu-cmake/files/10980397/build.gradle.txt)

**Comment by roussosalex** [comment]
I think that the problem may be related to this part of the log:

> ar: creating archive libicudata.a
  ranlib libicudata.a
  warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: libicudata.a the table of contents is empty (no object file members in the library define global symbols)

Looks like the cross compile always used the system ar/ranlib instead of the ones in the NDK toolchain. A similar issue was resolved [here](https://stackoverflow.com/q/9537964). I have pushed a fix to the dev-fix branch, if you could try it out and report if it works, with a new build log if it does not.

**Comment by bcortens** [comment]
Progress,

Compile time issues are no longer a problem but I am now seeing a runtime linker error...


```
2023-03-16 11:56:55.529 11404-11404/com.example.cmake_icu_test W/linker: Warning: "/data/app/~~iWr70RDZWprn3OF2KmgKsA==/com.example.cmake_icu_test-VJC_aye0G6f94Oljywi3ag==/base.apk!/lib/arm64-v8a/libicudata.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
2023-03-16 11:56:55.529 11404-11441/com.example.cmake_icu_test I/AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
2023-03-16 11:56:55.529 11404-11404/com.example.cmake_icu_test W/linker: Warning: "/data/app/~~iWr70RDZWprn3OF2KmgKsA==/com.example.cmake_icu_test-VJC_aye0G6f94Oljywi3ag==/base.apk!/lib/arm64-v8a/libicuio.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
2023-03-16 11:56:55.529 11404-11404/com.example.cmake_icu_test W/linker: Warning: "/data/app/~~iWr70RDZWprn3OF2KmgKsA==/com.example.cmake_icu_test-VJC_aye0G6f94Oljywi3ag==/base.apk!/lib/arm64-v8a/libicutu.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
2023-03-16 11:56:55.530 11404-11404/com.example.cmake_icu_test D/AndroidRuntime: Shutting down VM
2023-03-16 11:56:55.531 11404-11404/com.example.cmake_icu_test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.cmake_icu_test, PID: 11404
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6icu_7213UnicodeStringD1Ev" referenced by "/data/app/~~iWr70RDZWprn3OF2KmgKsA==/com.example.cmake_icu_test-VJC_aye0G6f94Oljywi3ag==/base.apk!/lib/arm64-v8a/libMyCPPLib.so"...
```

**Comment by roussosalex** [comment]
It looks like the linker warning means that the `DF_1_ORIGIN=0x80` flag is not supported. This may lead to the linker not considering the `$ORIGIN` rpath of the built libraries, thus not being able to find them. You may want to try to load the libraries manually using "System.loadLibrary(...)" in their reverse order of dependency, before loading your library:
```Java
static {
    System.loadLibrary("icudata");
    System.loadLibrary("icuuc");
    System.loadLibrary("icui18n");
    System.loadLibrary("icutu");
    System.loadLibrary("icuio");

    // load your library here
}
```

**Comment by bcortens** [comment]
Hello,

It works! Thank you very much for your assistance this week. 

Loading the icu libraries explicitly before my library and it now appears to work as expected. Was able to create some UnicodeStrings for grapheme processing without any issues. 

Compile SDK 31
NDK Version tested with both 21.4.7075529 and 25.1.8937393 and both succeeded.

**Comment by roussosalex** [comment]
Great!
