### ISSUE TITLE
Android Studio Running Error "dlopen failed"

### ISSUE THREAD

**Issue by Mlleters** [viaduck/icu-cmake#9]
Use the compiled so library in android studio, and use the so library to run in other projects. The error java.lang.UnsatisfiedLinkError: dlopen failed: library "libicuuc.so.72" not found: needed by /data/app/~~mzhgyZsBEUU1EHKCMEWatA ==/com.nova.myapplication-qhj2X7Lm_4w_N_zXnKJOAg==/base.apk!/lib/arm64-v8a/libmyapplication.so in namespace classloader-namespace

**Comment by Mlleters** [comment]
I manually updated the patch to solve the above problem, but now I get an error when running the program Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "utext_openUTF8_72" referenced by "/data/app/~~fY2ubyxbVAp0vAi7z-pzoQ==/com .nova.novatext-WUxpfUitvVWKHlFKzTGKvQ==/base.apk!/lib/arm64-v8a/libnovatypography.so"

**Comment by roussosalex** [comment]
First, it always helps if you include some of your code and the general setup to help our understanding of the issue. Are you using the prebuilts or building the ICU libraries?

> use the so library to run in other projects

How are you using the library in another library? Is it linked via CMake? Can you show some of that code and the build.gradle including the native part? How are you loading the library?

> I manually updated the patch

How did you update the patch, and which patch did you update?

As far as I understand the error, you may be experiencing the same loader issue as in #6, please try the suggestion https://github.com/viaduck/icu-cmake/issues/6#issuecomment-1472793065 (with the original state of the project) and report back.

**Comment by Mlleters** [comment]
Sorry, thank you for your help. This is the build.gradle and cmake files I used to compile the icu project. 
[build.gradle.kts.txt](https://github.com/viaduck/icu-cmake/files/14797678/build.gradle.kts.txt)
[CMakeLists.txt](https://github.com/viaduck/icu-cmake/files/14797679/CMakeLists.txt)

I found that the patch execution failed. I just manually updated 0010-fix-pkgdata-suffix.patch and 0023-remove-soname-version.patch without making other modifications.

I looked at issue #6 and it was successful after the build failed, which is the opposite of my situation.

**Comment by Mlleters** [comment]
[build.gradle.kts.txt](https://github.com/viaduck/icu-cmake/files/14797683/build.gradle.kts.txt)
[CMakeLists.txt](https://github.com/viaduck/icu-cmake/files/14797685/CMakeLists.txt)

**Comment by Mlleters** [comment]
This is the cmakelist file and running error file of the demo I use the icu lib
[CMakeLists.txt](https://github.com/viaduck/icu-cmake/files/14797700/CMakeLists.txt)

[RunError.txt](https://github.com/viaduck/icu-cmake/files/14797764/RunError.txt)

[native-lib.cpp.txt](https://github.com/viaduck/icu-cmake/files/14797768/native-lib.cpp.txt)

**Comment by roussosalex** [comment]
> I found that the patch execution failed

That is because you are using an old version. Please use `-DICU_BUILD_VERSION=74.2` in the build.gradle.

> I looked at issue https://github.com/viaduck/icu-cmake/issues/6 and it was successful after the build failed, which is the opposite of my situation.

How is it the opposite of your situation? According to the RunError log, you are only loading `libicudata.so`, the other libraries are missing. Please also provide the code where you load the libraries. All ICU libraries must be loaded in the order specified in https://github.com/viaduck/icu-cmake/issues/6#issuecomment-1472793065 _before_ loading any library requiring the ICU libraries.

**Comment by roussosalex** [comment]
Also, your `CMakeLists.txt` should not load the libraries manually. Please consider the following snippet:

```CMake
# add the icu-cmake project as a subdirectory to your project following the README.md "Usage" guide
add_subdirectory(icu-cmake)

# link your libraries and the "icu" target that already provides the libraries and the headers
target_link_libraries(${CMAKE_PROJECT_NAME} icu android log)
```

**Comment by Mlleters** [comment]
Sorry, as you said, you need to declare the order of loading libraries in java. Thank you for your support.
